export { default as Navbar } from './Navbar';
export { default as Hero } from './Hero';
export { default as FeatureCards } from './FeatureCards';
export { default as Platforms } from './Platforms';
export { default as Features } from './Features';
export { default as ComponentShowcase } from './ComponentShowcase';
export { default as Animations } from './Animations';
export { default as CTA } from './CTA';
export { default as Footer } from './Footer';
